type:           group
fields:

    seotitle:
      label:
        en: SEO Title
        de: SEO-Titel
      type: text
      icon: font
      width: 1/2
      required: true
    seotags:
      label: Keywords
      type: tags
      width: 1/2
    seometa:
      label:
        en: Meta Description
        de: Meta-Beschreibung
      type: textarea
      size: small
      buttons: false
      required: true
