label:                  SEO
icon:                   search
columns:
  # SEO Meta
  left:
    width:              2/3
    sections:

      seocontent:
        type:           fields
        fields:
          extends:      fields/seo/meta

  # Share Image
  right:
    width:              1/3
    sections:
      seomedia:
        type:           fields
        fields:
          shareimage:
            label:      Share Image
            type:       files
            uploads:
              template: shot
            width:      1/3
            max:        1
            info:       "{{ file.dimensions }}"
            image:
              ratio:    2/1

          indexfollwheadling:
            type: headline
            label: Search engine settings
            numbered: false
          noindex:
            type: toggle
            label: Enable noindex?
            text:
              - "index"
              - "noindex"
            default: false
          nofollow:
            type: toggle
            label: Enable nofollow?
            text:
              - "follow"
              - "nofollow"
            default: false

